version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 5000:5000
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5002:5000
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - server
