version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 5000:5000
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5002:5000
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - server
  vault:
    image: vault:1.12.7
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
