FROM python:3.13.0a6-slim

WORKDIR /app-client
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

RUN find / -xdev -perm /6000 -type f -exec chmod a-s {} \; || true
RUN  useradd client 
USER client

CMD ["python3", "-m", "flask", "--app", "client", "run", "--host=0.0.0.0"]
