FROM python:3.10
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install requests
COPY . .
EXPOSE 5011
CMD ["python3", "-m", "flask", "--app", "_old_main", "run", "--host=0.0.0.0", "-p 5011"]
