FROM python:3.13.0b1-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server .
RUN find / -xdev -perm /6000 -type f -exec chmod a-s {} \; || true
RUN  useradd server && chown server:server /app
USER server

CMD ["python3", "-m", "flask", "--app", "server", "run", "--host=0.0.0.0"]
