FROM python:3.10
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./server .
RUN find / -xdev -perm /6000 -type f -exec chmod a-s {} \; || true
RUN useradd server
USER server
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:5000/ || exit 1
CMD ["python3", "-m", "flask", "--app", "server", "run", "--host=0.0.0.0"]
