name: Blacktool

on: 
  pull_request:
    branches: [main,master]

jobs:
  blacktool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: true
          version: "21.5b1"