name: Create and publish a Docker image
on:
    pull_request:
        branches: [main, master]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3


        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ghcr.io/hfdevEX/app_flask:alpha
            