name: Pylint
on:
  pull_request:
    branches: [main, master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      # See https://stackoverflow.com/q/71086285
      run: |
        pylint $(git ls-files '*.py')
    - name: Post result
      uses: TheFoundryVisionmongers/fn-pylint-action@v1
      with:
        pylint-disable: "C,I,R"  # Only errors and warnings.
        pylint-rcfile: "./pyproject.toml"
        pylint-paths: "python tests"
    





